language: ruby
rvm:
- 2.2.5
script:
- jekyll build
before_install:
- openssl aes-256-cbc -K $encrypted_08d59baf4e3b_key -iv $encrypted_08d59baf4e3b_iv
  -in travis_rsa.enc -out travis_rsa -d
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
