language: ruby
rvm:
- 2.2.5
script:
- jekyll build
before_install:
before_deploy:
- openssl aes-256-cbc -K $encrypted_08d59baf4e3b_key -iv $encrypted_08d59baf4e3b_iv
  -in travis_rsa.enc -out /tmp/travis_rsa -d
- chmod 600 /tmp/travis_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/travis_rsa
- ssh-keyscan www.martin-helmich.de >> ~/.ssh/known_hosts
deploy:
  provider: script
  script: rsync -r -e "ssh -o StrictHostKeyChecking=no" --delete-after --quiet . travis@martin-helmich.de:/var/www/www.martin-helmich.de/
  skip_cleanup: true
  on:
    branch: master
